services:

  vite:
    container_name: ${APP_PROJECT_NAME}_vite
    image: oven/bun:latest
    working_dir: /app
    command: sh -c "bun install && bun run dev --host"
    environment:
      VIRTUAL_HOST: ${APP_DOMAINS_STRING}
      VIRTUAL_PORT: ${VITE_PORT:-8080}
      LETSENCRYPT_HOST: ${APP_DOMAINS_STRING}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-contact@wexample.com}
    volumes:
      - ${APP_PATH}:/app
      - vite_node_modules:/app/node_modules
    networks:
      wex_net:
        aliases:
          - vite

volumes:
  vite_node_modules:
